### ISSUE TITLE
Training code for VAE.

### ISSUE THREAD

**Issue by xuntianci** [1170300714/LP-DiF#1]
Hi, Thanks for sharing the paper and code. It is a great work!
Can you provide your code about training VAE? I can just find the /pre_calculate_GD and generate_GD.py .But I can't find training code for VAE. I also learn the code about SHIP, but SHIP not provide the datasets.py for cifar100.
Can you help me? Thanks!

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by xuntianci** [comment]
![QQ截图20240305115120](https://github.com/1170300714/LP-DiF/assets/138184818/e8bb1ec5-5284-4243-ac79-5d082f30f4c9)
How can I  get the generated feature? Use CLIP pretraind ViT-b/16 ?

**Comment by 1170300714** [comment]
Thank you for your attention. The author responsible for tunning the VAE module is currently busy with another work and may need to wait for some time before it can be opened source. We apologize for any inconvenience caused.

For generate features, it consists of two parts. One is the image encoder pre trained by CLIP (such as ViT b/16), which you can call the ZeroshotCLIP class in [this file](https://github.com/KaiyangZhou/CoOp/blob/main/trainers/zsclip.py) to extract the true features of the training image. The second is the pseudo features generated by VAE. In fact, according to the results of the ablation experiment in our paper, the performance improvement of LP-DiF is mainly due to the Gaussian distribution composed of real features, while the pseudo features generated by VAE play an additional role. So you can prioritize using real features to complete your experiment.

**Comment by xuntianci** [comment]
Thank you for your reply!
